---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "*"
      sinks:
          - meter_sink
    - name: cpu_source
      interval: 600
      meters:
          - "cpu"
      sinks:
          - cpu_sink
    - name: memory_source
      interval: 600
      meters:
          - "memory.usage"
      sinks:
          - memory_sink
    - name: disk_source
      interval: 600
      meters:
          - "disk.read.bytes"
          - "disk.read.requests"
          - "disk.write.bytes"
          - "disk.write.requests"
      sinks:
          - disk_sink
    - name: disk_root_used_source
      interval: 600
      meters:
          - "disk.root.size.used"
      sinks:
          - disk_root_used_sink
    - name: disk_ephemeral_used_source
      interval: 600
      meters:
          - "disk.ephemeral.size.used"
      sinks:
          - disk_ephemeral_used_sink    
    - name: network_source
      interval: 600
      meters:
          - "network.incoming.bytes"
          - "network.incoming.packets"
          - "network.outgoing.bytes"
          - "network.outgoing.packets"
      sinks:
          - network_sink
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - rpc://
    - name: cpu_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - rpc://
    - name: memory_sink
      transformers:
          - name: "unit_conversion"
            parameters:
                target:
                    name: "memory.usage.percent"
                    unit: "%"
                    type: "gauge"
                    scale: "volume * 100.0 / resource_metadata.memory_mb"
      publishers:
          - rpc://
    - name: disk_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "disk\\.(read|write)\\.(bytes|requests)"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "disk.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - rpc://
    - name: disk_root_used_sink
      transformers:
          - name: "unit_conversion"
            parameters:
                target:
                    name: "disk.root.size.used.percent"
                    unit: "%"
                    type: "gauge"
                    scale: "volume * 100.0 / resource_metadata.disk_gb"
      publishers:
          - rpc://
    - name: disk_ephemeral_used_sink
      transformers:
          - name: "unit_conversion"
            parameters:
                target:
                    name: "disk.ephemeral.size.used.percent"
                    unit: "%"
                    type: "gauge"
                    scale: "volume * 100.0 / resource_metadata.ephemeral_gb"
      publishers:
          - rpc://          
    - name: network_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - rpc://
